# Generated by Django 4.1.4 on 2022-12-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('actif', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Apparetement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('surface', models.FloatField()),
                ('nombre_piece', models.IntegerField()),
                ('Id_programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PromgrammeImmo.programme')),
            ],
        ),
    ]
