# Generated by Django 4.1.4 on 2022-12-16 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PromgrammeImmo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Apparetement',
            new_name='Appartement',
        ),
    ]
