# Generated by Django 4.1.4 on 2022-12-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromgrammeImmo', '0002_rename_apparetement_appartement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='appartement',
            name='caracteristiques',
            field=models.ManyToManyField(to='PromgrammeImmo.caracteristique'),
        ),
    ]
