# Generated by Django 4.1.4 on 2022-12-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PromgrammeImmo', '0003_caracteristique_appartement_caracteristiques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartement',
            name='caracteristiques',
            field=models.ManyToManyField(related_name='descriptions', to='PromgrammeImmo.caracteristique'),
        ),
    ]
